export const SET_SERVERLESS_URI = 'SET_SERVERLESS_URI';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
export const SET_SYNC_TOKEN = 'SET_SYNC_TOKEN';

export const SET_STATS_PAGE_STATE = 'SET_STATS_PAGE_STATE';
export const INITIATE_TASK_STATS = 'INITIATE_TASK_STATS';
export const UPDATE_TASK_STATS = 'UPDATE_TASK_STATS';
export const REMOVE_TASK_STATS = 'REMOVE_TASK_STATS';
export const INITIATE_WORKER_STATS = 'INITIATE_WORKER_STATS';
export const UPDATE_WORKER_STATS = 'UPDATE_WORKER_STATS';
export const REMOVE_WORKER_STATS = 'REMOVE_WORKER_STATS';
