export const SET_SERVERLESS_URI = 'SET_SERVERLESS_URI';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
export const SET_SYNC_TOKEN = 'SET_SYNC_TOKEN';

export const SET_STATS_PAGE_STATE = 'SET_STATS_PAGE_STATE';
